events {}

http {
    server {
        listen 80;
        server_name ip24kk1.sit.kmutt.ac.th;

        location /itb-mshop/ {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /itb-mshop/index.html;
        }
    }
}
