server {
    listen 80;
    server_name ip24kk1.sit.kmutt.ac.th;

    root /usr/share/nginx/html;
    index index.html;

    # location / {
    #     root /usr/share/nginx/html/;
    #     index index.html;
    #     try_files $uri $uri/ /index.html;
    #      add_header Cache-Control "no-cache";
    # }

    # Frontend 
    location /kk1/ {
        try_files $uri $uri/ /kk1/index.html;
    }

    location /kk1/ {
        add_header Cache-Control "no-cache";
    }

    # Backend
     location /kk1/itb-mshop/v1/ {
        proxy_pass http://backend:8080/kk1/itb-mshop/v1/;
        proxy_set_header Host $host;
    }

    
}