server {
    listen 80;
    server_name intproj24.sit.kmutt.ac.th;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /kk1/itb-mshop/index.html;
        add_header Cache-Control "no-cache";
    }

   location /kk1/itb-mshop/v1/ {
    proxy_pass http://api:8080;
}
}
