services:
  frontend:
    build: 
      context: ./client
    ports:
     - "80:80"
    networks:
    - kk1-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 64M
        reservations:
          memory: 16M
    restart: unless-stopped  
  database:
    build: 
      context: ./database
    container_name: database
    environment:
     - MYSQL_ROOT_PASSWORD=root
    networks:
     - kk1-network
    ports:
     - "3306:3306"
    healthcheck:
      test: ["CMD","mysqladmin", "ping", "-h", "database"]
      interval: 20s
      timeout: 20s
      retries: 5
      start_period: 40s 
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 512M
        reservations:
          memory: 400M
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
  
  api:
    build:
      context: ./server
    container_name: api
    ports:
      - "8000:8080"
    depends_on:
      database:
        condition: service_healthy   
    networks:
      - kk1-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 384M
        reservations:
          memory: 256M
    restart: unless-stopped

networks:
  kk1-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local