# spring.datasource.url=jdbc:mysql://database:3306/mobile_shop?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
# spring.datasource.username=root
# spring.datasource.password=${file:/run/secrets/db_password}

# app.origins=http://intproj24.sit.kmutt.ac.th,http://ip24kk1.sit.kmutt.ac.th
# logging.level.root=DEBUG
# server.error.include-stacktrace=never

spring.datasource.url=jdbc:mysql://database:3306/mobile_shop?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
logging.level.root=DEBUG
app.origins=http://intproj24.sit.kmutt.ac.th,http://ip24kk1.sit.kmutt.ac.th
server.error.include-stacktrace=never

