
name: Deploy kk1 update clear cache

on:
  push:
    branches:
      - pre-dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Auto Deploy container application itb-mshop 
        env:
          GH_PAT_TOKEN: ${{ secrets.GH_PAH_TOKEN }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          set -x  
          cd /home/sysadmin/2-2567_INT221_KK-1 

          git pull https://napatzzz:${GH_PAT_TOKEN}@github.com/Derlariel/2-2567_INT221_KK-1.git pre-dev
          
          mkdir -p /tmp/db_secrets
          echo "${DB_PASSWORD}" > /tmp/db_secrets/db_password
          
          mkdir -p secrets
          cp /tmp/db_secrets/db_password secrets/db_password || true

        

          docker compose down -v
          docker compose build --no-cache
          docker compose up -d 
          docker image prune -f
          # docker builder prune -f 